### ISSUE TITLE
CSV_EXPORT2 fails if no `parameters.txt`

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#187]
The CSV_EXPORT2 job fails if there is no parameters.txt in the runpath. This will occur if the parameterisation is described without using GEN_KW.

**Steps to reproduce**
This is most interesting to reproduce with a forward model that creates summary data, as that is part of the output CSV_EXPORT2 grabs and exports. Create a setup with either no uncertain parameters (based on SPE1), or only SURFACE, GEN_PARAM etc and run it. Try to export using CSV_EXPORT2 and watch it fail.

**Comment by asnyv** [comment]
This probably belongs in its own issue, but:
Would also be nice to be able to deactivate the merging of parameters into the time dependent data, even with existing parameter data (export only summary data), and vice-versa (export only parameters, with no time dependency). 

Both because merging creates unnecessary copies of parameter values (storage), and because it might be easier to usae the data if you have explicit information on what is parameters, and what is summary results.

**Comment by berland** [comment]
In that case, I would say that the ERT config should not use CSV_EXPORT2 at all, but rather obtain only the summary data directly, through ERT API, or through other means (ECL2CSV + optionally CSV_MERGE (subscript)).

**Comment by asnyv** [comment]
Just thinking user simplicity here @berland: think many ERT users are familiar with CSV_EXPORT jobs from "the old days", and include them no matter what. 

Of course quite easy to do the same thing by combining other jobs, or making your own, but this is so "basic" that I think it might be worth supporting (if it was up to me, we wouldn't merge these files by default at all, but think we've had that discussion before 😉)

**Comment by berland** [comment]
With ERT API and Webviz, there should not be any need at all for this workflow - that is the simplest we can get :)

**Comment by asnyv** [comment]
That's true 😄
