### ISSUE TITLE
[MPP] Job failed because of empty dataset

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#242]
@wouterjdb reported that the job failed due to missing realizations with error: 

```
The script 'MisfitPreprocessorJob' caused an error while running:
This operation results in an empty dataset (could be due to one or more failed realizations)
```

This should be investigated, as a failed realization should not cause the job to fail, this error message should be improved if the cause of the crash was something else.

Might need access to test data to replicate this case, as the test suite should have a case with failed realizations that behaves as expected.

**Comment by wouterjdb** [comment]
I don't think that this was a problem in the end. I tested it on a case with two simulations only - and both of them failed.

Maybe the error message could be updated as "one or [a few]" failed realizations should be filtered out and wouldn't cause this error? This should only happens when all simulations have failed (or fewer than some threshold). The error message could reflect that.

**Comment by oyvindeide** [comment]
Ok, good. Yes, I agree. I will keep the issue open then, as the error message needs to be updated.

**Comment by oyvindeide** [comment]
Error message should now be improved when we try to read them from `ert`, closing.
