### ISSUE TITLE
[DP] Write to parameters.json

### ISSUE THREAD

**Issue by berland** [equinor/semeio#54]
design2params should possibly write to `parameters.json` as well as `parameters.txt`

**Comment by markusdregi** [comment]
We've discussed sensitivity analysis earlier together @eivindsm and in the future we would like this to be an integrated part of ERT instead of a feature available through forward model tooling. However, as long as the script is still alive, this could be a good step in the direction of getting rid of the `parameters.txt`-file 👍

**Comment by oyvindeide** [comment]
This is solved by dumping the full se
