### ISSUE TITLE
equinor test data not available where we run komodo ci

### ISSUE THREAD

**Issue by jondequinor** [equinor/semeio#73]
Or is it? I don't know. The folder `ErtTestData` seems to not exist.

**Comment by markusdregi** [comment]
It is not. In my opinion we should strive to get rid of the dependency on Equinor test data. It is not very nice to depend on private testing data in an open source project. There are many hurdles to this and normally the large datasets are too large to be used for efficient debugging anyway. Hence, the tests are worth much less than carefully crafted fake datasets.

**Comment by oyvindeide** [comment]
The main reason for relying on the `ErtTestData` is because it is the only source of some observation types (as far as I can tell), and that is needed because the logic for setting scaling factor lives in `semeio`. Once new storage is up and running and there is a suitable API, that should be removed and we should only use open data. I will close this issue now, because it is not really actionable.
