### ISSUE TITLE
Unphysical /unlogical results from COS job

### ISSUE THREAD

**Issue by eivindsm** [equinor/semeio#96]
I strongly suspect a bug in the COS job based on test results that I regard to be unphysical / unlogical. I have a test setup with three datatypes (wct, shutin, and rft). My legacy code estimates npca = 5, 2, 4, 7 for wct, shutin, rft, and all of them together. The COS job, however, estimates 3,1,1,1, respectively. 

Minor deviations from legacy script might be explained by cut-off and outlayers, but not this severe. It is also suspicious that the number of eigenvectors estimated by COS decrease when adding more observations.

Case:  /project/fmu/users/eism/ERT_COS/r005/ert/model/

**Comment by oyvindeide** [comment]
Thanks for testing! During testing, did you look at the matrix that went into the PCA calculation? There _should not_ be any difference with regards to outliers and cut-off, as the defaults are the same, so I do not think the problem lies there (not to say that it does not), and as you say, the difference is so large that should not be the problem, which points to something else.

**Comment by eivindsm** [comment]
No, did not get into that level of detail. One of the obs-groups only had 5 observations, so it is viable to compare legacy code with COS. A couple of things to check: scaling of the observations (the fact that adding more observations decreases NPCA, point to variance being dominated by a few points), normal scoring, make sure the number of PCs are determined based on variance and not std.
